// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9xNCtD9W5DRF7Dt0E-RGsparfr2sBqwU',
    appId: '1:1074628879571:web:1350c16275afca824ca026',
    messagingSenderId: '1074628879571',
    projectId: 'fir-appdist-d86fa',
    authDomain: 'fir-appdist-d86fa.firebaseapp.com',
    storageBucket: 'fir-appdist-d86fa.appspot.com',
    measurementId: 'G-M9YZPE5YM6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDilmQpK3wprNBeaagb6MaNX9wBZ_hDHvY',
    appId: '1:1074628879571:android:49b23e22fe6c5eaf4ca026',
    messagingSenderId: '1074628879571',
    projectId: 'fir-appdist-d86fa',
    storageBucket: 'fir-appdist-d86fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdGt1M9udn8asOdZHJl68BcNLC5_3O4aY',
    appId: '1:1074628879571:ios:aa8737f2d8acd49d4ca026',
    messagingSenderId: '1074628879571',
    projectId: 'fir-appdist-d86fa',
    storageBucket: 'fir-appdist-d86fa.appspot.com',
    iosBundleId: 'com.example.firebaseAppDist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdGt1M9udn8asOdZHJl68BcNLC5_3O4aY',
    appId: '1:1074628879571:ios:7c60039f696ae7444ca026',
    messagingSenderId: '1074628879571',
    projectId: 'fir-appdist-d86fa',
    storageBucket: 'fir-appdist-d86fa.appspot.com',
    iosBundleId: 'com.example.firebaseAppDist.RunnerTests',
  );
}
